## invalid 
## Age invalie 
## card 
CODE_VALID = 0 
CODE_UNAUTHORIZED = 404 
CODE_INVALID_AGE = 422
CODE_INVALID_TYPE = 423
CODE_USER_EXISTS = 424

DETAIL_DATA_VALID = "Valid"
DETAIL_INVALID_AGE= "Age is invalid"
DETAIL_INVALID_TYPE= "Type is invalid"
DETAIL_UNAUTHORIZED = "May be unauthorized"
CODE_USER_EXISTS = "Info is duplicate or database error, try again"


map_err = {
    CODE_VALID: DETAIL_DATA_VALID, 
    CODE_INVALID_AGE: DETAIL_INVALID_AGE, 
    CODE_INVALID_TYPE: DETAIL_INVALID_TYPE, 
    CODE_UNAUTHORIZED: DETAIL_UNAUTHORIZED, 
    CODE_USER_EXISTS: CODE_USER_EXISTS, 
}

